# Generated by Django 3.2.23 on 2024-01-15 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='namne',
            new_name='name',
        ),
    ]
